apiVersion: v1
kind: Template
metadata:
  name: openfact-search-pe
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      service: openfact-search-pe
    name: openfact-search-pe
  spec:
    replicas: 1
    selector:
      service: openfact-search-pe
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: openfact-search-pe
      spec:
        containers:
        - image: openfact/openfact-search-pe-openshift:latest
          imagePullPolicy: Always
          name: openfact-search-pe
          ports:
          - containerPort: 80
            protocol: TCP
          env:
            - name: PROXY_PASS_URL
              valueFrom:
                configMapKeyRef:
                  name: openfact-search-pe
                  key: proxy.pass.url
            - name: OPENFACT_API_URL
              valueFrom:
                configMapKeyRef:
                  name: openfact-search-pe
                  key: openfact.api.url
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 10
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: openfact-search-pe
    name: openfact-search-pe
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: openfact-search-pe
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      service: openfact-search-pe
    name: openfact-search-pe
  spec:
    host: ''
    port:
      targetPort: "8080"
    to:
      kind: Service
      name: openfact-search-pe
      weight: 100
    wildcardPolicy: None
  status: {}
parameters:
- name: IMAGE_TAG
  value: latest
